networks:
  api_network:
    driver: bridge
volumes:
  db-store:

services:
  db:
    container_name: db_container
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: app
      MARIADB_DATABASE: db_app
      MARIADB_USER: root
      MARIADB_PASSWORD: app
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - db-store:/var/lib/mysql
    networks:
      - api_network
  app:
    container_name: app_container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/php.init:/usr/local/etc/php/php.init
      - ./public:/var/www/html/public
    networks:
      - api_network
    environment:
      MARIADB_HOST: db
      MARIADB_PORT: 3306
      MARIADB_DATABASE: db_app
      MARIADB_USER: root
      MARIADB_PASSWORD: app
  nginx:
    container_name: nginx_container
    image: nginx:latest
    restart: always
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    ports:
      - 9001:80
    networks:
      - api_network
    depends_on:
      - app